### ISSUE TITLE
Generating Message-ID header

### ISSUE THREAD

**Issue by surajwy** [nodemailer/buildmail#13]
Hi,

Is there a reason for why we are not using a GUID/UUID at https://github.com/nodemailer/buildmail/blob/master/lib/buildmail.js#L805 place?
We could use modules like node-uuid and generate a v4 id out of it and use it as Message-ID.
Apple mail client is also using a similar approach. 

Please let me know if I am missing something.

Thanks,
Suraj

**Comment by andris9** [comment]
Left part of Message-Id does not have restrictions on the format used as long as it is unique. There is no value in using uuid and I want to keep the dependency tree of Nodemailer as simple as possible.

**Comment by andris9** [comment]
If you really need to have uuid values in Message-Id fields then you can create these like this:

```javascript
mail = {
    from: '...,
    messageId: uuid.v4() + '@domain.tld'
}
```

**Comment by surajwy** [comment]
Thanks, Andris for a quick reply.

**Comment by andris9** [comment]
Btw, if you create your own message-id values, then the domain in the messageId should either be the reverse resolved hostname of the server sending the messages or the domain of the from address. Using something else might result in spam points.
