### ISSUE TITLE
Flowed not honoring new lines

### ISSUE THREAD

**Issue by devlo** [nodemailer/buildmail#6]
On Thunderbird flowed not honoring new lines.. 
Example from source of received e-mail: 
```
Content-Type: text/plain; format=flowed
Content-Transfer-Encoding: 7bit

Line one
Line Two
Line Three
```
Will show content in one line like this:

```
Line one Line Two Line Three
```

I am using nodemailer, for now i just commented build-mail flowed.   
I could use buffer in nodemailer but I do not want to use new Buffer to turn off flowed because it's not a clean solution for this (not efficient, some spam engines can mark it as spam because of encoding/special chars)

Any planned fix for that? I think option to turn off flowed in nodemailer would be the best.. Because it's not only thunderbird problem.. 
Besides that i don't see major clients adding flowed as default so.. maybe it's not such a good idea..

**Comment by andris9** [comment]
format=flowed is not used anymore, starting from buildmail 3.0.0
