### ISSUE TITLE
Errors in content stream are not caught

### ISSUE THREAD

**Issue by wearhere** [nodemailer/buildmail#7]
If the content can't be encoded (e.g. because the message is malformed), then [the content stream](https://github.com/andris9/buildmail/blob/master/src/buildmail.js#L551) will emit an error. This error will not be caught—there is an error handler on the "local" stream but not the content stream.

I would argue that `buildmail` should catch this error like it does that occurring in the local stream. In any case, since `createReadStream` doesn't return the content stream but rather the output stream to which the content stream pipes, the application can't catch such errors (by attaching an error handler to the result of `createReadStream`).

**Comment by andris9** [comment]
Do you have any examples that would make content stream to throw? Content stream uses either libqp or libbase64 which are not supposed to throw.

**Comment by andris9** [comment]
Fixed in v3.0.0

**Comment by wearhere** [comment]
Nice!
